### ISSUE TITLE
Problem of "_pickle.UnpicklingError: pickle data was truncated"

### ISSUE THREAD

**Issue by AnderDong** [barisgecer/OSTeC#13]
First of all, thank you very much for sharing such excellent work! When I complete the installation, and run "python run_ostec.py --source_dir [source_dir] --save_dir [save_dir] [-f] -i [iterations (default 200)] -m [soft|hard|auto]", the error occurrs：

`Using TensorFlow backend.
/***/***/***/***/miniconda3/envs/ostec/lib/python3.6/site-packages/kornia/augmentation/augmentation.py:1875: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
Traceback (most recent call last):
  File "/***/***/***/***/OSTeC/external/arcface50.py", line 19, in load_weights
    weights_dict = np.load(weight_file).item()
  File "/***/***/***/***/miniconda3/envs/ostec/lib/python3.6/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/***/***/***/***/miniconda3/envs/ostec/lib/python3.6/site-packages/numpy/lib/format.py", line 693, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_ostec.py", line 76, in <module>
    main(args)
  File "run_ostec.py", line 28, in main
    operator = Operator(args)
  File "/***/***/***/***/OSTeC/core/operator.py", line 112, in __init__
    self.arcface_handler = Arcface_Handler()
  File "/***/***/***/***/OSTeC/core/arcface_handler.py", line 85, in __init__
    self.emb_norm, _, _, vars = identity_features(aligned_img, 'input_id_features')
  File "/***/***/***/***/OSTeC/core/arcface_handler.py", line 74, in identity_features
    input, embedding, content = arcface50.KitModel('models/fr_models/arcface50.npy', input * 255)
  File "/***/***/***/***/OSTeC/external/arcface50.py", line 28, in KitModel
    __weights_dict = load_weights(weight_file)
  File "/***/***/***/***/OSTeC/external/arcface50.py", line 21, in load_weights
    weights_dict = np.load(weight_file, encoding='bytes').item()
  File "/***/***/***/***/miniconda3/envs/ostec/lib/python3.6/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/***/***/***/***/miniconda3/envs/ostec/lib/python3.6/site-packages/numpy/lib/format.py", line 693, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated`

Looking for your reply. Thank you very much!

**Comment by leenaltwayan** [comment]
Hello, im facing the same issue right now, could you tell me how you were able to solve it?

**Comment by Kopamed** [comment]
I also have the same issue

**Comment by create-li** [comment]
I also have the same issue
